// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"example/gthomework/work3/internal/biz/dal/dao"
	"example/gthomework/work3/internal/biz/dal/mysql"
	"example/gthomework/work3/internal/biz/handler"
	"example/gthomework/work3/internal/biz/service"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeEvent() (*handler.UserHandler, error) {
	db := mysql.GetDB()
	userDao := dao.NewUserDao(db)
	userService := service.NewUserService(userDao)
	userHandler := handler.NewUserHandler(userService)
	return userHandler, nil
}
